spring:
  datasource:
    username: root
    password: Harsh@123
    url: jdbc:mysql://localhost:3306/auth
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true  


server:
  port: 8081  